language: node_js
# nodejs版本
node_js:
  - '14.16.0'

# S: Build Lifecycle
install:
  - npm install
script:
  - npm run build

# 这个是不是看着很熟悉？
after_script:
  - cd ./build
  - git init
  - git config user.name ${U_NAME}
  - git config user.email ${U_EMAIL}
  - git add .
  - git commit -m "auto publish svelte.cookbook"
  - git push --force --quiet "https://${token}@${GH_REF} main:${P_branch}
# E: Build LifeCycle

# 只对某个分支行为生效
branches:
  only:
    - main